apiVersion: apps/v1
kind: Deployment
metadata:
  name: javascript-deployment
  labels:
    app: javascript-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javascript-app
  template:
    metadata:
      labels:
        app: javascript-app
    spec:
      containers:
        - name: javascript
          image: cgaksapp.azurecr.io/js-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: javascript-service
  labels:
    app: javascript-app
spec:
  type: LoadBalancer
  selector:
    app: javascript-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000