apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress-deploy
  labels:
    app: mongoexpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
        - name: mongodb-express
          image: mongo-express
          ports: 
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: admin
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: password  
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb-service            
     
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service
spec:
  selector:
    app: mongodb-express
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001 